apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: book-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-server
  template:
    metadata:
      labels:
        app: book-server
    spec:
      containers:
          - name: book-server
            image: shudipta/book_server:v1
            ports:
              - containerPort: 10000
---
apiVersion: v1
kind: Service
metadata:
  name:  book-server-service
  labels:
    app: book-server
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 10000
  type: NodePort
  selector:
    app: book-server
