apiVersion: v1
kind: ServiceAccount
metadata:
  name: ctl-svc-acc
  namespace: default
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: ctl-role
rules:
- apiGroups: ["samplecrdcontroller.crd.com"]
  resources: ["somethings"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
---

# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ctl-role-binding
subjects:
- kind: ServiceAccount
  name: ctl-svc-acc
  namespace: default
#  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: ctl-role
  apiGroup: rbac.authorization.k8s.io
